// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Confiteria.Infraestructura.AccesoDatos;

public partial class Clientes
{
    public int IdCliente { get; set; }

    public string NombreCliente { get; set; }

    public string TipoCliente { get; set; }

    public string Contacto { get; set; }

    public virtual ICollection<Pedidos> Pedidos { get; set; } = new List<Pedidos>();
}