// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Confiteria.Infraestructura.AccesoDatos;

public partial class Pedidos
{
    public int IdPedido { get; set; }

    public int IdCliente { get; set; }

    public DateOnly FechaPedido { get; set; }

    public DateOnly? FechaEntrega { get; set; }

    public string EstadoPedido { get; set; }

    public virtual ICollection<DetallePedido> DetallePedido { get; set; } = new List<DetallePedido>();

    public virtual Clientes IdClienteNavigation { get; set; }
}