// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Confiteria.Infraestructura.AccesoDatos;

public partial class Productos
{
    public int IdProducto { get; set; }

    public string NombreProducto { get; set; }

    public decimal PrecioUnitario { get; set; }

    public virtual ICollection<DetallePedido> DetallePedido { get; set; } = new List<DetallePedido>();
}