// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Confiteria.Infraestructura.AccesoDatos;

public partial class Usuarios
{
    public int IdUsuario { get; set; }

    public string Nombre { get; set; }

    public string Email { get; set; }

    public string Contraseña { get; set; }

    public int IdRol { get; set; }

    public virtual Roles IdRolNavigation { get; set; }
}